name: tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Copy .env.ci
        run: cp .env.ci .env

      - name: Generate application keys
        run: php artisan key:generate

      - name: Run tests
        run: vendor/bin/phpunit
